apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-deployer-trackme
  namespace: mignon-tokyo
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: github-deployer-trackme-token
  namespace: mignon-tokyo
  labels:
    app.kubernetes.io/name: trackme
    app.kubernetes.io/part-of: mignon-ci
  annotations:
    kubernetes.io/service-account.name: github-deployer-trackme
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-deployer-trackme
  namespace: mignon-tokyo
rules:
  - apiGroups: [apps]
    resources: [deployments]
    resourceNames: [trackme]
    verbs: [get, patch, update, watch]
  - apiGroups: [apps]
    resources: [replicasets]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [pods, events]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-deployer-trackme
  namespace: mignon-tokyo
subjects:
  - kind: ServiceAccount
    name: github-deployer-trackme
    namespace: mignon-tokyo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-deployer-trackme
